Switch /cert to /loadCerts API call when configuring DIND credentials (as it can be used from the "general" users' accounts)

diff --git a/workflows/pipe-common/shell/docker_setup_credentials b/workflows/pipe-common/shell/docker_setup_credentials
--- a/workflows/pipe-common/shell/docker_setup_credentials
+++ b/workflows/pipe-common/shell/docker_setup_credentials
@@ -22,59 +22,35 @@ if [ "$1" == "--skip-cert" ]; then
     _DIND_SKIP_CERTS_SETUP=1
 fi
 
-if [ -z "$CP_CAP_DIND_REGISTRY_HOST" ]; then
-    CP_CAP_DIND_REGISTRY_HOST="$(echo "$docker_image" | cut -d "/" -f1)"
-fi
-
-if [ -z "$CP_CAP_DIND_REGISTRY_HOST" ]; then
-    echo "Unable to determine default registry host to configure docker credentials"
-    exit 1
-fi
-
 ###############################################################
-# Get the id of the CP_CAP_DIND_REGISTRY_HOST registry
-###############################################################
-_DIND_REGISTRY_ID=$(curl -s \
-                    --max-time 30 \
-                    -X GET \
-                    --insecure \
-                    --header "Accept: application/json" \
-                    --header "Authorization: Bearer $API_TOKEN" \
-                    "$API/dockerRegistry/loadTree" | jq -r ".payload.registries[] | select(.path == \"$CP_CAP_DIND_REGISTRY_HOST\").id // 0")
-
-if [ "$_DIND_REGISTRY_ID" == 0 ]; then
-    echo "Cannot determine id of the registry, containing  "
-    exit 1
-fi
-echo "Registry ($CP_CAP_DIND_REGISTRY_HOST) id is: $_DIND_REGISTRY_ID"
-
-###############################################################
-# Setup certificate of the CP_CAP_DIND_REGISTRY_HOST registry
+# Setup certificates and login to the available registries
 ###############################################################
 if [ -z "$_DIND_SKIP_CERTS_SETUP" ]; then
-    _DIND_REGISTRY_CERTS_DIR="/etc/docker/certs.d/$CP_CAP_DIND_REGISTRY_HOST"
-    mkdir -p $_DIND_REGISTRY_CERTS_DIR
-    curl -k -s --header "Authorization: Bearer $API_TOKEN" \
-        -o $_DIND_REGISTRY_CERTS_DIR/ca.crt \
-        $API/dockerRegistry/$_DIND_REGISTRY_ID/cert
-    
+    _DIND_REGISTRIES_JSON=$(curl -k -s --fail --header "Authorization: Bearer $API_TOKEN" $API/dockerRegistry/loadCerts)
     if [ $? -ne 0 ]; then
-        echo "Unable to configure certificate for $CP_CAP_DIND_REGISTRY_HOST registry"
+        echo "Cannot get the list of the certificates for the docker registries"
         exit 1
-    else
-        echo "Registry certificate is configured"
     fi
-else
-    echo "Registry certificate will be skipped"
-fi
 
-###############################################################
-# Login to the CP_CAP_DIND_REGISTRY_HOST registry
-###############################################################
-docker login "$CP_CAP_DIND_REGISTRY_HOST" -u "$OWNER" --password-stdin <<< "$API_TOKEN" > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-    echo "Unable to configure docker credentials for $CP_CAP_DIND_REGISTRY_HOST registry and $OWNER user"
-    exit 1
+    _DIND_REGISTRIES_LIST=$(echo "$_DIND_REGISTRIES_JSON" | jq -r '.payload | keys[]')
+    while read _DIND_REGISTRY_NAME; do
+        echo "Configuring certificates and credentials for $_DIND_REGISTRY_NAME registry"
+        _DIND_REGISTRY_CERTS_DIR="/etc/docker/certs.d/$_DIND_REGISTRY_NAME"
+        mkdir -p $_DIND_REGISTRY_CERTS_DIR
+        echo $_DIND_REGISTRIES_JSON | jq -r ".payload.\"${_DIND_REGISTRY_NAME}\"" > $_DIND_REGISTRY_CERTS_DIR/ca.crt
+        echo "ca.crt is written to $_DIND_REGISTRY_CERTS_DIR/ca.crt"
+
+        # Login to the registry
+        docker login "$_DIND_REGISTRY_NAME" -u "$OWNER" --password-stdin <<< "$API_TOKEN" > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "Unable to configure docker credentials for $_DIND_REGISTRY_NAME registry and $OWNER user"
+            continue
+        else
+            echo "Docker credentials are configured for $_DIND_REGISTRY_NAME registry and $OWNER user"
+        fi
+    done <<<$_DIND_REGISTRIES_LIST
+    
+    echo "Registry certificates and credentials are configured"
 else
-    echo "Docker credentials are configured"
+    echo "Registry certificates and credentials configuration will be skipped"
 fi
