Respect CP_CAP_SGE_PREINSTALLED for ubuntu SGE worker
(cherry picked from commit d35c38a7be9515829a7ddd7cf1faae39130ef58a)

diff --git a/workflows/pipe-common/shell/sge_setup_worker b/workflows/pipe-common/shell/sge_setup_worker
--- a/workflows/pipe-common/shell/sge_setup_worker
+++ b/workflows/pipe-common/shell/sge_setup_worker
@@ -186,8 +186,11 @@ fi
 
 if [ "$LINUX_DISTRIBUTION" = "debian" ]; then
     export SGE_ROOT="/var/lib/gridengine"
-    rm -rf /var/lib/gridengine/
-    apt-get remove gridengine-client gridengine-common gridengine-master gridengine-exec --purge -y
+
+    if [ "$CP_CAP_SGE_PREINSTALLED" != "true" ]; then
+        rm -rf /var/lib/gridengine/
+        apt-get remove gridengine-client gridengine-common gridengine-master gridengine-exec --purge -y
+    fi
 
     echo "gridengine-common       shared/gridenginemaster string  $MASTER_NAME" |  debconf-set-selections
     echo "gridengine-common       shared/gridenginecell   string  default" |  debconf-set-selections
@@ -197,20 +200,22 @@ if [ "$LINUX_DISTRIBUTION" = "debian" ]; then
     echo "gridengine-client       shared/gridengineconfig boolean false" |  debconf-set-selections
     echo "postfix postfix/main_mailer_type        select  No configuration" |  debconf-set-selections
 
-    CP_CAP_SGE_VERSION="${CP_CAP_SGE_VERSION:-8.1.9+dfsg-4*}"
+    if [ "$CP_CAP_SGE_PREINSTALLED" != "true" ]; then
+        CP_CAP_SGE_VERSION="${CP_CAP_SGE_VERSION:-8.1.9+dfsg-4*}"
 
-    # First install SGE, and fail if error occurs
-    DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" gridengine-exec="$CP_CAP_SGE_VERSION" \
-        gridengine-client="$CP_CAP_SGE_VERSION" \
-        gridengine-common="$CP_CAP_SGE_VERSION" > /dev/null
+        # First install SGE, and fail if error occurs
+        DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" gridengine-exec="$CP_CAP_SGE_VERSION" \
+            gridengine-client="$CP_CAP_SGE_VERSION" \
+            gridengine-common="$CP_CAP_SGE_VERSION" > /dev/null
 
-    check_last_exit_code $? "All SGE packages were installed" "Fail to install SGE worker"
+        check_last_exit_code $? "All SGE packages were installed" "Fail to install SGE worker"
 
-    # Next - try to install any non-mandatory packages, and igore them if error occurs
-    DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" sudo locales > /dev/null
+        # Next - try to install any non-mandatory packages, and igore them if error occurs
+        DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" sudo locales > /dev/null
 
-    if [ $? -ne 0 ]; then
-        pipe_log_warn "Additional SGE packages were not installed, error is ignored" "$SGE_MASTER_SETUP_TASK"
+        if [ $? -ne 0 ]; then
+            pipe_log_warn "Additional SGE packages were not installed, error is ignored" "$SGE_MASTER_SETUP_TASK"
+        fi
     fi
 
     ## Configure default locale, see https://github.com/rocker-org/rocker/issues/19
