Allow to switch between old and news hosts management using env var

diff --git a/workflows/pipe-common/shell/wait_for_host_resolving b/workflows/pipe-common/shell/wait_for_host_resolving
--- a/workflows/pipe-common/shell/wait_for_host_resolving
+++ b/workflows/pipe-common/shell/wait_for_host_resolving
@@ -30,25 +30,26 @@
 WORKER_HOST="$1"
 WORKER_IP="$2"
 
-CP_CAP_AUTOSCALE_HOSTS_RESOLVING_ATTEMPTS="${CP_CAP_AUTOSCALE_HOSTS_RESOLVING_ATTEMPTS:-12}"
-CP_CAP_AUTOSCALE_HOSTS_RESOLVING_DELAY="${CP_CAP_AUTOSCALE_HOSTS_RESOLVING_DELAY:-5}"
+CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_ATTEMPTS="${CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_ATTEMPTS:-12}"
+CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_DELAY="${CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_DELAY:-5}"
 
-for host_resolving_attempt in $(seq 1 "$CP_CAP_AUTOSCALE_HOSTS_RESOLVING_ATTEMPTS"); do
+for host_resolving_attempt in $(seq 1 "$CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_ATTEMPTS"); do
     if [[ -z "$WORKER_IP" ]]; then
         getent hosts "$WORKER_HOST" | grep "\s\+$WORKER_HOST\$" > /dev/null
     else
         getent hosts "$WORKER_HOST" | grep "^$WORKER_IP\s\+$WORKER_HOST\$" > /dev/null
     fi
     host_resolving_exit_code=$?
-    if [[ $host_resolving_exit_code -eq 0 ]]; then
+    if [[ "$host_resolving_exit_code" == "0" ]]; then
         break
     fi
-    echo "Host resolving has failed after $host_resolving_attempt/$CP_CAP_AUTOSCALE_HOSTS_RESOLVING_ATTEMPTS attempts. Trying again in $CP_CAP_AUTOSCALE_HOSTS_RESOLVING_DELAY seconds."
-    sleep "$CP_CAP_AUTOSCALE_HOSTS_RESOLVING_DELAY"
+    echo "Host resolving has failed after $host_resolving_attempt/$CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_ATTEMPTS attempts. Trying again in $CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_DELAY seconds."
+    sleep "$CP_CAP_AUTOSCALE_DNS_HOSTS_RESOLVE_DELAY"
 done
 
-if [[ $host_resolving_exit_code -ne 0 ]]
+if [[ "$host_resolving_exit_code" != "0" ]]
 then
     echo "Host resolving has failed. Exiting..."
-    exit 1
 fi
+
+exit "$host_resolving_exit_code"
