jump-server.yaml description  and parameter naming fixes

diff --git a/deploy/infra/aws/cloudformation/jump-server.yaml b/deploy/infra/aws/cloudformation/jump-server.yaml
--- a/deploy/infra/aws/cloudformation/jump-server.yaml
+++ b/deploy/infra/aws/cloudformation/jump-server.yaml
@@ -1,18 +1,29 @@
 AWSTemplateFormatVersion: '2010-09-09'
-Description: Create Jump-box EC2 instance
+Description: >
+  Deploy Cloud-Pipeline solution on top of AWS infrastructure. 
+  As a first step this stack will spin up EC2 instance that will work as a Jump Server to deploy Cloud-Pipeline solution itself. 
+  On the second step EC2 instance will run terraform deployment to deploy all required AWS infrastructure to host Cloud-Pipeline. 
+  During the final, third step, pipectl deployment command will be executed on top of the created AWS infrastructure to finally deploy all EKS resource and configure Cloud-Pipeline. 
+
 
 Parameters:
-  ProjectName:
+  DeploymentName:
     Type: String
     Description: (Required) Name of the deployment. Will be used as resources name prefix
-  Env:
+  DeploymentEnv:
     Type: String
     Description: (Required) Environment name. Will be used as resources name prefix
+  DeploymentAWSCredentialsSecretId:
+    Type: String
+    Description: >
+      (Optional) If not set the TFDeployRole will be created with full administator access and assumed to Jump-Server role.
+      Name of the aws secret with secret key and access key of the user that will be used on JumpServer to run Terraform to deploy infrastructure
+    Default: ""
   JumpServerInstanceType:
     Type: String
     Description: (Optional) Jump-server EC2 instance type
     Default: t3.medium
-  AmiId:
+  JumpServerAmiId:
     Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
     Description: (Optional) Image id that will be used for Jump-Server
     Default: /aws/service/eks/optimized-ami/1.29/amazon-linux-2/recommended/image_id
@@ -20,83 +31,88 @@ Parameters:
     Type: String
     Description: (Required) Id of the VPC where all resources will be created
     Default: ""
-  CPInfraSubnetId:
-    Type: String
-    Description: (Required) Subnet where JumpServer instance and EKS node group will be created
-    Default: ""
-  EKSSubnetIds:
+  SubnetIds:
     Type: String
     Description: (Required) Ids of the VCP subnets to be used for Cloud Pipeline EKS cluster, FS mount points, etc. At least one subnet id in list must be specified
     Default: ""
-  IAMrolePermissionsBoundaryArn:
+  EKSAdminRoleArns:
     Type: String
-    Description: (Optional) Account specific role boundaries
+    Description: > 
+      (Optional) Set of roles ARNs which will get admin access in EKS cluster. 
+      Could be useful if DeploymentAWSCredentialsSecretId is not provided. Then here user can provide ARN of his role to get access to the cluster.
     Default: ""
-  FileSystemType:
+  IAMRolePermissionsBoundaryArn:
     Type: String
-    Description: (Optional) FileSystem type that will be created. Can be efs or fsx. Default efs.
-    Default: "efs"
+    Description: (Optional) Account specific role boundaries, this value will be used for all created IAM Roles.
+    Default: ""
   TFstateBucketName:
     Type: String
     Description: (Required) S3 Bucket name, that will be created where terraform state file for Cloud-Pipeline Infrastructure module will be stored
   TFStateLockTableName:
     Type: String
     Description: (Required) Name of the DynamoDB table, that will be created, for terraform state lock
-  CPApiAccessPrefixLists:
+  CPSystemSubnetId:
     Type: String
-    Description: (Optional) Prefix Lists to which access to Cloud Pipeline API will be granted
+    Description: (Required) Subnet where JumpServer instance and Cloud-Pipeline system EKS node group (where Cloud-Pipeline internal components will be deployed) will be created
+    Default: ""
+  CPNetworkFileSystemType:
+    Type: String
+    Description: (Optional) FileSystem type that will be created. Can be efs or fsx. Default efs
+    Default: "efs"
+  CPAccessPrefixLists:
+    Type: String
+    Description: (Optional) AWS Prefix Lists to which access to Cloud Pipeline will be granted
     Default: ""
   CPDeploymentId:
     Type: String
-    Description: (Optional) Specify unique ID of the deployment. It will be used to name cloud entities (e.g. path within a docker registry object container). Must contain only letters, digits, underscore or horizontal bar.
+    Description: >
+      (Optional) Specify unique ID of the Cloud-Pipeline deployment. 
+      It will be used to name cloud entities (e.g. path within a docker registry object container). 
+      Must contain only letters, digits, underscore or dash
     Default: "Cloud-Pipeline"
-  CPEdgeAwsElbSubnets:
+  CPEdgeAwsElbSubnet:
     Type: String
-    Description: (Required) The ID of the public subnet for the Load Balancer. Must be in the same Availability Zone (AZ) as the CPInfraSubnetId.
+    Description: >
+      (Required) The ID of the public subnet for the Load Balancer to be created. 
+      Must be in the same Availability Zone (AZ) as the CPSystemSubnetId
     Default: ""
-  CPEdgeAwsElbEipallocs:
+  CPEdgeAwsElbEIPAlloc:
     Type: String
-    Description: (Required) Allocation ID of the created Elastic IP
+    Description: (Required) Allocation ID of the Elastic IP from prerequisites. See README.md for more information
     Default: ""
-  CPPrefUiPipelineDeploymentName:
-    Type: String
-    Description: (Optional) Deployment Name that will be shown as the browser tab name
-    Default: "Cloud-Pipeline"  
   CPApiSrvHost:
     Type: String
-    Description: (Required) API service domain name address
-  CPIdpHost:
-    Type: String
-    Description: (Required) IDP service domain name address
-    Default: ""
+    Description: (Required) API service domain name address. See README.md for more information
   CPDockerHost:
     Type: String
-    Description: (Required) Docker service domain name address
+    Description: (Required) Docker service domain name address. See README.md for more information
   CPEdgeHost:
     Type: String
-    Description: (Required) EDGE service domain name address
+    Description: (Required) EDGE service domain name address. See README.md for more information
   CPGitlabHost:
     Type: String 
-    Description: (Required) GITLAB service domain name address
-  EKSAdminRoleArns:
+    Description: (Required) GITLAB service domain name address. See README.md for more information
+  CPIdpHost:
     Type: String
-    Description: (Optional) If secret with aws credentials not specified then set arn of the role wich will get admin access in EKS cluster
-    Default: ""
-  AWSCredentialSecretId:
-    Type: String
-    Description: (Optional, if not set the TFDeployRole will be created with full administator access and assumed to Jump-Server role) Name of the aws secret with secret key and access key of the user that will be used on Jumpserver to run Terraform to deploy infrastructure
+    Description: > 
+      (Optional) Self hosted IDP service domain name address. 
+      WARNING: Using self hosted IDP service in production environment strongly not recommended!
+      If not provided CPAssetsS3Url parameter should be provided with all necessary artifacts to configure SSO authentication for Cloud-Pipeline. 
+      See README.md for more information
     Default: ""
   CPAssetsS3Url:
-    Type: String 
-    Description: (Optional) Link to zip archive with additional assets on AWS S3 bucket. For example s3://<bucket-name>/<filename.zip>
-    Default: ""
-  PipectlUrl:
     Type: String
-    Description: Link to the latest pipectl binary file that will be user to deploy Cloud Pipeline
+    Description: >
+      (Optional) Link to zip archive with additional assets on AWS S3 bucket. For example s3://<bucket-name>/<filename.zip>. 
+      See README.md for more information
+    Default: ""
+  CPPipectlUrl:
+    Type: String
+    Description: (Required) Link to the pipectl binary file that will be used to deploy Cloud Pipeline
 
 Conditions:
-    IsSecretNotEntered: !Equals [!Ref AWSCredentialSecretId, ""]
-    IsBoundaryNotEntered: !Equals [!Ref IAMrolePermissionsBoundaryArn, ""]
+    IsSecretNotEntered: !Equals [!Ref DeploymentAWSCredentialsSecretId, ""]
+    IsBoundaryNotEntered: !Equals [!Ref IAMRolePermissionsBoundaryArn, ""]
 
 Resources:
 
@@ -124,9 +140,9 @@ Resources:
     JumpServerIAMRole:
       Type: 'AWS::IAM::Role'
       Properties:
-        RoleName: !Sub "${ProjectName}-${Env}-JumpServer-role"
+        RoleName: !Sub "${DeploymentName}-${DeploymentEnv}-JumpServer-role"
         Path: /
-        PermissionsBoundary: !If [IsBoundaryNotEntered, !Ref AWS::NoValue, !Ref IAMrolePermissionsBoundaryArn ]
+        PermissionsBoundary: !If [IsBoundaryNotEntered, !Ref AWS::NoValue, !Ref IAMRolePermissionsBoundaryArn ]
         AssumeRolePolicyDocument:
           Version: 2012-10-17
           Statement:
@@ -137,7 +153,7 @@ Resources:
               Action:
                 - 'sts:AssumeRole'
         Policies:
-         - PolicyName: !Sub ${ProjectName}-${Env}-JumpServer-read-secret
+         - PolicyName: !Sub ${DeploymentName}-${DeploymentEnv}-JumpServer-read-secret
            PolicyDocument:
              Version: 2012-10-17
              Statement:
@@ -164,9 +180,9 @@ Resources:
       Type: 'AWS::IAM::Role'
       Condition: IsSecretNotEntered
       Properties:
-        RoleName: !Sub "${ProjectName}-${Env}-tf-deploy-infra-role"
+        RoleName: !Sub "${DeploymentName}-${DeploymentEnv}-tf-deploy-infra-role"
         Path: /
-        PermissionsBoundary: !If [IsBoundaryNotEntered, !Ref AWS::NoValue, !Ref IAMrolePermissionsBoundaryArn ]
+        PermissionsBoundary: !If [IsBoundaryNotEntered, !Ref AWS::NoValue, !Ref IAMRolePermissionsBoundaryArn ]
         MaxSessionDuration: 7200
         AssumeRolePolicyDocument:
           Version: 2012-10-17
@@ -182,7 +198,7 @@ Resources:
     JumpboxSG:
       Type: AWS::EC2::SecurityGroup
       Properties:
-        GroupDescription: !Sub "${ProjectName}-${Env}-jumpserver-sg"
+        GroupDescription: !Sub "${DeploymentName}-${DeploymentEnv}-jumpserver-sg"
         VpcId: !Ref VpcId
         SecurityGroupIngress:
           - IpProtocol: '-1'
@@ -199,11 +215,11 @@ Resources:
       DependsOn: TerraformS3Bucket
       Properties:
         IamInstanceProfile: !Ref JumpServerInstanceProfile
-        ImageId: !Ref AmiId
+        ImageId: !Ref JumpServerAmiId
         InstanceType: !Ref JumpServerInstanceType
         SecurityGroupIds: 
           - !GetAtt JumpboxSG.GroupId
-        SubnetId: !Ref CPInfraSubnetId
+        SubnetId: !Ref CPSystemSubnetId
         UserData: 
           "Fn::Base64": !Sub | 
               #!/bin/bash
@@ -239,7 +255,7 @@ Resources:
               terraform {
                 backend "s3" {
                   bucket         = "${TFstateBucketName}"
-                  key            = "${Env}/terraform.tfstate"
+                  key            = "${DeploymentEnv}/terraform.tfstate"
                   region         = "${AWS::Region}"
                   encrypt        = true
                   dynamodb_table = "${TFStateLockTableName}"
@@ -288,19 +304,18 @@ Resources:
 
               module "cluster-infra" {
                 source                            = "git::https://github.com/epam/cloud-pipeline//deploy/infra/aws/terraform/cloud-native/cluster-infra?ref=f_aws_native_infra"
-                project_name                      = "${ProjectName}"
-                env                               = "${Env}"
+                project_name                      = "${DeploymentName}"
+                env                               = "${DeploymentEnv}"
                 vpc_id                            = "${VpcId}"
-                cp_api_access_prefix_lists        = ["${CPApiAccessPrefixLists}"]
-                subnet_ids                        =  tolist([for subnet in split(",", "${EKSSubnetIds}"): trimspace(subnet)]) 
-                iam_role_permissions_boundary_arn = "${IAMrolePermissionsBoundaryArn}" 
-                eks_system_node_group_subnet_ids  =  ["${CPInfraSubnetId}"]
-                deploy_filesystem_type            =  "${FileSystemType}"
-                deployment_id                     =  "${CPDeploymentId}"
-                elb_public_subnet                 =  "${CPEdgeAwsElbSubnets}"
-                eipalloc                          =  "${CPEdgeAwsElbEipallocs}"
+                cp_api_access_prefix_lists        = ["${CPAccessPrefixLists}"]
+                subnet_ids                        =  tolist([for subnet in split(",", "${SubnetIds}"): trimspace(subnet)]) 
+                iam_role_permissions_boundary_arn = "${IAMRolePermissionsBoundaryArn}" 
+                eks_system_node_group_subnet_ids  =  ["${CPSystemSubnetId}"]
+                deploy_filesystem_type            =  "${CPNetworkFileSystemType}"
+                cp_deployment_id                  =  "${CPDeploymentId}"
+                cp_edge_elb_public_subnet         =  "${CPEdgeAwsElbSubnet}"
+                cp_edge_eipalloc                  =  "${CPEdgeAwsElbEIPAlloc}"
                 cp_api_srv_host                   =  "${CPApiSrvHost}"
-                ui_deployment_name                =  "${CPPrefUiPipelineDeploymentName}" 
                 cp_idp_host                       =  "${CPIdpHost}"
                 cp_docker_host                    =  "${CPDockerHost}"
                 cp_edge_host                      =  "${CPEdgeHost}"
@@ -347,14 +362,14 @@ Resources:
               }
               EOF
               
-              export CP_SECRET=${AWSCredentialSecretId}
+              export CP_SECRET=${DeploymentAWSCredentialsSecretId}
               if [ -n "$CP_SECRET"  ]; then
                  creds=$(aws secretsmanager get-secret-value --secret-id $CP_SECRET  --query SecretString --output text  --region ${AWS::Region})
                  eval $creds
               else   
                  export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
                  $(aws sts assume-role \
-                 --role-arn arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-${Env}-tf-deploy-infra-role \
+                 --role-arn arn:aws:iam::${AWS::AccountId}:role/${DeploymentName}-${DeploymentEnv}-tf-deploy-infra-role \
                  --role-session-name TFDeploy \
                  --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                  --output text))
@@ -406,7 +421,7 @@ Resources:
                   cd ~/deployment-eks
               fi
               
-              wget -c ${PipectlUrl} -O pipectl
+              wget -c ${CPPipectlUrl} -O pipectl
               chmod +x pipectl
               terraform output -raw cp_pipectl_script > deploycp.sh && chmod +x deploycp.sh
               ./deploycp.sh > pipectl.log
@@ -414,14 +429,14 @@ Resources:
               cat << EOF > delete_all_cp_infra.sh
               #!/bin/bash
               echo "-----------SET ACCESS TO AWS-----------------" 
-              export CP_SECRET=${AWSCredentialSecretId}
+              export CP_SECRET=${DeploymentAWSCredentialsSecretId}
               if [ -n "$CP_SECRET"  ]; then
                   creds=\$(aws secretsmanager get-secret-value --secret-id $CP_SECRET  --query SecretString --output text  --region ${AWS::Region})
                   eval \$creds
               else   
                   export \$(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
                   \$(aws sts assume-role \
-                  --role-arn arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-${Env}-tf-deploy-infra-role \
+                  --role-arn arn:aws:iam::${AWS::AccountId}:role/${DeploymentName}-${DeploymentEnv}-tf-deploy-infra-role \
                   --role-session-name TFDeploy \
                   --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                   --output text))
@@ -436,15 +451,20 @@ Resources:
               done
 
               if [ "\$APPROVE" == "TRUE" ]; then
-                 echo "-----------START DESTROYING RESOURCES!-------------------"
-                 kubectl delete service ingress
-
-                 terraform destroy --auto-approve
-
-                 aws s3 rm s3://${TFstateBucketName} --recursive
-                 echo "-----------INFRASTRUCTURE RESOURSES DESTROYED!-------------------"
-                 echo "-----------NOW YOU CAN DELETE CLOUDFORMATION STACK!-------------------"
-              else echo "-----------DELETION ABORTED!-------------------"
+                 echo "START DESTROYING TERRAFORM RESOURCES!"
+                 
+                 kubectl delete service ingress && \
+                   terraform destroy --auto-approve
+                  
+                 if [ "\$?" -ne 0 ]; then
+                    echo "Something went wrong during automated resources deletion process! Manual intervention is required!"
+                    exit 1
+                 else
+                    aws s3 rm s3://${TFstateBucketName} --recursive
+                    echo "INFRASTRUCTURE RESOURCES DESTROYED! NOW YOU CAN DELETE CLOUDFORMATION STACK!"
+                 fi
+              else 
+                 echo "DELETION ABORTED!"
               fi
               EOF
 
@@ -453,7 +473,11 @@ Resources:
               
         Tags:
         - Key: Name
-          Value: !Sub "${ProjectName}-${Env}-JumpServer"      
+          Value: "${DeploymentName}-${DeploymentEnv}-JumpServer"
+        - Key: Deployment
+          Value: !Sub "${DeploymentName}"
+        - Key: Environment
+          Value: !Sub "${DeploymentEnv}"
 
 Outputs:
   InstanceID:
