issue 1349 mount aws and gcp containers to web dav with pipe mount

diff --git a/deploy/docker/cp-dav/init b/deploy/docker/cp-dav/init
--- a/deploy/docker/cp-dav/init
+++ b/deploy/docker/cp-dav/init
@@ -23,6 +23,14 @@ export APACHE_LOG_DIR="${APACHE_LOG_DIR:-/var/log/dav/httpd}"
 export SYNC_LOG_DIR="${SYNC_LOG_DIR:-/var/log/dav/sync}"
 export APACHE_DAV_LOCK_DB="${APACHE_DAV_LOCK_DB:-$APACHE_HOME/dav/DavLock}"
 
+function download_file {
+    local _FILE_URL=$1
+    echo "Downloading ${_FILE_URL}"
+    wget -q --no-check-certificate ${_FILE_URL} 2>/dev/null || curl -s -k -O ${_FILE_URL}
+    _DOWNLOAD_RESULT=$?
+    return "$_DOWNLOAD_RESULT"
+}
+
 if [ -z "$API" ] && ([ -z "$CP_API_SRV_INTERNAL_HOST" ] || [ -z "$CP_API_SRV_INTERNAL_PORT" ]); then
     echo "$API is not set, and we cannot construct it as $CP_API_SRV_INTERNAL_HOST or $CP_API_SRV_INTERNAL_PORT are not set as well, exiting"
     exit 1
@@ -34,6 +42,21 @@ if [ -z "$API_TOKEN" ] && [ -z "$CP_API_JWT_ADMIN" ]; then
     exit 1
 fi
 export API_TOKEN="${API_TOKEN:-$CP_API_JWT_ADMIN}"
+
+export DISTRIBUTION_URL="${DISTRIBUTION_URL:-https://${CP_API_SRV_INTERNAL_HOST}:${CP_API_SRV_INTERNAL_PORT}/pipeline/pipe.tar.gz}"
+download_file "${DISTRIBUTION_URL}"
+
+if [ $? -eq 0 ]; then
+      echo "[ERROR] 'pipe' CLI download succeeded."
+      cp pipe.tar.gz /opt/ && \
+      cd /opt && \
+      tar -zxf pipe.tar.gz && \
+      rm -rf pipe.tar.gz && \
+      ln -s /opt/pipe/pipe /usr/bin/pipe
+      if [ $? -eq 0 ]; then
+        pipe configure --auth-token "$API_TOKEN" --api "${API}" --timezone local --proxy ''
+      fi
+fi
 
 # Create the required directories
 mkdir -p "$CP_DAV_SERVE_DIR" "$CP_DAV_MOUNT_POINT" "$APACHE_LOG_DIR" "$SYNC_LOG_DIR"
